name: deploy
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Print working directory
      run: pwd
    -
      name: List files in root directory
      run: ls -la
    -
      name: List files in back/ecommerce-m-2018 directory
      run: ls -la back/ecommerce-m-2018
    -
      name: Check Dockerfile existence
      run: |
        if [ -f back/ecommerce-m-2018/Dockerfile ]; then
          echo "Dockerfile exists"
          cat back/ecommerce-m-2018/Dockerfile
        else
          echo "Dockerfile does not exist"
          echo "Contents of back/ecommerce-m-2018 directory:"
          ls -la back/ecommerce-m-2018
        fi
    -
      name: Login To Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Build
      uses: docker/setup-buildx-action@v3
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./back/ecommerce-m-2018
        file: ./back/ecommerce-m-2018/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nest-demo:latest
